config/routes.rb
BolaoApp::Application.routes.draw do

  resources :match_results
  resources :games
  resources :teams
  resources :hints
  resources :users

  root :to => 'main#index'

  match 'admin/index' => 'admin#index', :as => :admin

  match 'index' => 'main#index', :as => :index
  match 'cadastro' => 'main#cadastro', :as => :cadastro
  match 'ranking' => 'main#ranking', :as => :ranking
  match 'regras' => 'main#regras', :as => :regras

  match 'login/index' => 'login#index', :as => :login
  match 'login/do_login' => 'login#do_login', :as => :login_do_login
  match 'login/do_logout' => 'login#do_logout', :as => :logout

  match 'hints/result/savehint' => 'hints#saveHint', :as => :save_hint
  match 'hints/result/allhints' => 'hints#all_hints', :as => :all_hints  
  match 'hints/result/adminallhints' => 'hints#admin_all_hints', :as => :admin_all_hints
  match 'hints/result/calculator' => 'hints#calculator', :as => :calculator
  match 'hints/result/get_statistics' => 'hints#get_statistics', :as => :get_statistics

  match 'users/:id/reset_score' => 'users#reset_score', :as => :user_reset_score
  match 'users/calculate/reset_all_scores' => 'users#reset_all_scores', :as => :reset_all_scores
  match 'users/calculate/reset_all_hintspoints' => 'users#reset_all_hintspoints', :as => :reset_all_hintspoints

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  skip_before_filter :require_login, :require_admin
  
  def index
  	respond_to do |format|
      format.html #index.html.erb
    end
  end

  def regras
  	respond_to do |format|
      format.html #regras.html.erb
    end
  end

  def cadastro
  	redirect_to controller: :users, action: :new
  end

  def ranking

    @users = User.all(:order => 'score DESC')

  	respond_to do |format|
      format.html #ranking.html.erb
    end
  end

  def current_logged_user
    Rails.logger.info("Passando pelo current_logged_user")
    if logged_in?
      @user = current_user
    else
      @user = nil
    end
    Rails.logger.info("*************************")
    Rails.logger.info(@user)
  end

end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_bottom.html.erb
<div id="bottom">
	<div class="wrap">
		<ul>
                <li><a href="<%=index_path%>" >O Bolão</a></li>
                <li><a href="<%=regras_path%>" >Regras</a></li>
                <li><a href="<%=ranking_path%>" >Cadastro</a></li>
                <li><a href="<%=cadastro_path%>" >Ranking</a></li>
      	</ul>         
		<div class="copyright">
      <p>-----------------------------------------</p>
      <p>Administrador: Gilliard Alan</p>
      <p>Email: gilalan@gmail.com</p>
      <p>-----------------------------------------</p>
		</div>
	</div>
</div>

app/views/main/_header.html.erb
<div id="header">
  <% if !@user.nil? %>
    <div id="logoutcontainer"> 
      <a id="userlogged" href="<%=hints_path%>" title="Página de Palpites"><%=@user.name%>&nbsp;<%=@user.lastname%></a>
      <a href="<%=logout_path%>" id="logout" alt="Sair" title="Sair">Sair</a>
    </div>
  <%end%>
    
  <div class="wrap">
    <a href="<%=login_path%>" id="login" alt="Entrar" title="Login"></a>
    <div class="top">
      <div class="mid">
        <a href="/" class="logo" alt="Bolão dos TOAs" title="Bolão da Copa das Confederações"></a>
      </div>
      <div id="menu">
        <div>
          <h3>
            Bolão dos Amigos!
          </h3>
          <h4>
            Copa do Mundo 2014
          </h4>
        </div>
        <ul>
          <li><a href="<%=index_path%>"><p>O Bolão</p></a></li>
          <li><a href="<%=regras_path%>"><p>Regras</p></a></li>
          <li><a href="<%=cadastro_path%>"><p>Cadastro</p></a></li>
          <li><a href="<%=ranking_path%>"><p>Ranking</p></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/main/ranking.html.erb
<h2>Ranking</h2>
<div class="premio">
	<img src="<%=asset_path('money.png')%>" style="float:left;margin-top:-15px;"/>
	<label style="padding:10px;">Prêmio: R$<%=User.where("typeof != 1").count * 15%></label>
</div>
<div class="ranking_list">
	<ul>
		<% position = 1 %>
		<% @users.each do |user| %>
			<% unless user.typeof == 1 %>
			  <li>
			    <div class="user_position">
			      <span><%=position%>º</span>
			    </div>
			    <div class="user_img_name">
			    	<% imgpath = "player_#{position}.png" %>
			        <img src="<%=asset_path(imgpath)%>"/>
			        <label><%="#{user.name} #{user.lastname}"%></label>
			    </div>
			    <div class="user_score">
			      <label><%=user.score%> pts</label>
			    </div>
			  </li>
			  <% position+=1 %>
			<% end %>
		<% end %>
	</ul>
</div>

<script type="text/javascript">
	
	jQuery(function(){

		jQuery(jQuery("#header #menu ul li")[3]).find("p").addClass("current");
	});
	
</script>

app/views/main/regras.html.erb
<h2>Regra para os Palpites</h2>
<h3>
	Os palpites dos jogos devem ser inseridos e editados até 30 minutos antes de cada partida, após isso, não será mais permitido a inserção/edição do palpite. 
	Após terminar esse tempo limite para inserção/edição dos palpites, será liberado a página de "transparência dos resultados para próxima partida", onde cada pessoa poderá visualizar os placares inseridos pelos outros participantes, tornando o bolão transparente para ninguém chorar depois dizendo que teve arrumadinho ;)
</h3>
<h2>Regra de Pontuação</h2>
<h3>
	<ul>
		<li>
			10 pontos: acertou o <b>placar exato</b> da partida.
		</li>
		<li>
			07 pontos: acertou o <b>resultado (quem venceu ou perdeu)</b> mas só acertou o número de gols de uma das equipes.
		</li>
		<li>
			05 pontos: acertou o <b>resultado (vencedor, perdedor ou empate)</b>, porém não acertou o número de gols de nenhuma das equipes.
		</li>
		<li>
			02 pontos: errou o <b>resultado (vencedor, perdedor ou empate)</b>, porém acertou o número de gols de uma das equipes.
		</li>
		<li>
			00 pontos: acertar PN.
		</li>
	</ul>
	<br>
	Exemplos de pontuação para um jogo com placar: Brasil 3 x 0 França.
	<br>
	<br>
	<ul>
		<li>
			João colocou Bra 3 x 0 Fra, ganhou 10 pontos pois acertou o placar exato da partida.
		</li>
		<li>
			José colocou Bra 3 x 1 Fra, ganhou 07 pontos pois acertou o resultado (Brasil venceu) e acertou o número de gols do Brasil.
		</li>
		<li>
			Marcos colocou Bra 4 x 0 Fra, ganhou 07 pontos pois acertou o resultado (Brasil venceu) e acertou o número de gols da França.		
		</li>
		<li>
			Lucas colocou Bra 2 x 1 Fra, ganhou 05 pontos pois acertou o resultado (Brasil venceu) mas errou o número de gols marcados por cada equipe.
		</li>
		<li>
			Silva colocou Bra 0 x 0 Fra, ganhou 02 pontos pois errou o resultado (Brasil venceu, ele colocou empate) mas acertou o número de gols de uma das equipes (da França no caso).
		</li>
		<li>
			Gilliard colocou Brasil 0 x 1 França, errou o resultado (Brasil venceu e ele colocou vitória da França) e errou também o número de gols de cada equipe.
		</li>
	</ul>
</h3>

<script type="text/javascript">
	
	jQuery(function(){

		jQuery(jQuery("#header #menu ul li")[1]).find("p").addClass("current");
	});
	
</script>