config/routes.rb
BolaoApp::Application.routes.draw do

  resources :match_results
  resources :games
  resources :teams
  resources :hints
  resources :users

  root :to => 'main#index'

  match 'admin/index' => 'admin#index', :as => :admin

  match 'index' => 'main#index', :as => :index
  match 'cadastro' => 'main#cadastro', :as => :cadastro
  match 'ranking' => 'main#ranking', :as => :ranking
  match 'regras' => 'main#regras', :as => :regras

  match 'login/index' => 'login#index', :as => :login
  match 'login/do_login' => 'login#do_login', :as => :login_do_login
  match 'login/do_logout' => 'login#do_logout', :as => :logout

  match 'hints/result/savehint' => 'hints#saveHint', :as => :save_hint
  match 'hints/result/allhints' => 'hints#all_hints', :as => :all_hints  
  match 'hints/result/adminallhints' => 'hints#admin_all_hints', :as => :admin_all_hints
  match 'hints/result/calculator' => 'hints#calculator', :as => :calculator
  match 'hints/result/get_statistics' => 'hints#get_statistics', :as => :get_statistics

  match 'users/:id/reset_score' => 'users#reset_score', :as => :user_reset_score
  match 'users/calculate/reset_all_scores' => 'users#reset_all_scores', :as => :reset_all_scores
  match 'users/calculate/reset_all_hintspoints' => 'users#reset_all_hintspoints', :as => :reset_all_hintspoints

end

app/models/hint.rb
class Hint < ActiveRecord::Base

  default_scope order('team_id ASC')

  attr_accessible :goals, :game_id, :user_id, :team_id, :points

  belongs_to :game
  belongs_to :team
  belongs_to :user

end

app/controllers/hints_controller.rb
class HintsController < ApplicationController
  
  skip_before_filter :require_admin, :except => :admin_all_hints

  # GET /hints
  # GET /hints.json
  def index
    
    if !current_user.nil?
      @user = current_user
    end

    Rails.logger.info(@user.to_yaml)

    @games = Game.all(:include => :match_results, :order => 'gamedate ASC, gametime ASC')

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /hints/1
  # GET /hints/1.json
  def show
    @hint = Hint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hint }
    end
  end

  # GET /hints/new
  # GET /hints/new.json
  def new
    @hint = Hint.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hint }
    end
  end

  # GET /hints/1/edit
  def edit
    @hint = Hint.find(params[:id])
  end

  # POST /hints
  # POST /hints.json
  def create
    @hint = Hint.new(params[:hint])

    respond_to do |format|
      if @hint.save
        format.html { redirect_to @hint, notice: 'Hint was successfully created.' }
        format.json { render json: @hint, status: :created, location: @hint }
      else
        format.html { render action: "new" }
        format.json { render json: @hint.errors, status: :unprocessable_entity }
      end
    end
  end

  def create user_id, team_id, game_id, goals
   
    Hint.transaction do
      begin 
        @hint = Hint.new(:user_id => user_id, :team_id => team_id, :game_id => game_id, :goals => goals)
        
        if !@hint.save
          return false
        else
          return true
        end

      rescue => e
        logger.error e.message
        print e.to_s + "\n" + e.backtrace.join("\n")
      end
    end

  end

  # PUT /hints/1
  # PUT /hints/1.json
  def update
    @hint = Hint.find(params[:id])

    respond_to do |format|
      if @hint.update_attributes(params[:hint])
        format.html { redirect_to @hint, notice: 'Hint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hint.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def updateGoals hint, goals
    Hint.transaction do
      begin
        hint.update_attributes(:goals => goals)
      rescue => e
        logger.error e.message
        print e.to_s + "\n" + e.backtrace.join("\n")
      end
    end
  end

  # DELETE /hints/1
  # DELETE /hints/1.json
  def destroy
    @hint = Hint.find(params[:id])
    @hint.destroy

    respond_to do |format|
      format.html { redirect_to hints_url }
      format.json { head :no_content }
    end
  end

  def saveHint
    hints = params[:array_hints] if params[:array_hints].present?
    Rails.logger.info(hints.inspect)
    #Rails.logger.info(hints.class.name)
    savedAll = true

    #This is a HashWithIndifferentAccess array
    hints.each do |index, jhint|

      jhint.each do |key, value|
        if key.eql?("teamid")
          @team_id = value
        elsif key.eql?("gameid")
          @game_id = value
        elsif key.eql?("userid")
          @user_id = value
        elsif key.eql?("goals")
          @goals = value  
        end
      end

      record = Game.find(@game_id).hints.find_all_by_user_id_and_team_id(@user_id, @team_id)
      
      if record.empty?
        savedAll = create(@user_id, @team_id, @game_id, @goals)
      else
        updateGoals(record.first, @goals)
      end

    end

    respond_to do |format|
      Rails.logger.info('TESTE DE RETORNO DA VARIAVEL SAVED DO SAVEHINT')
      Rails.logger.info(savedAll)
      format.json { render json: {saved: savedAll} }
    end
  end

  def all_hints
    
    if !current_user.nil?
      @user = current_user
    end

    @games = Game.all(:include => :match_results, :order => 'gamedate ASC, gametime ASC')
    @users = User.all(:include => :hints, :order => 'name ASC, lastname ASC')

    respond_to do |format|
      format.html #all_hints
    end
  end

  def admin_all_hints

    if !current_user.nil?
      @user = current_user
    end
    
    @games = Game.all(:include => :match_results, :order => 'gamedate ASC, gametime ASC')
    @users = User.all(:include => :hints, :order => 'name ASC, lastname ASC')

    respond_to do |format|
      format.html #admin_all_hints
    end
  end

  def calculator
    games = Game.where(:closed => true).where(:finished => true).where(:computed => false)
    users = User.where("typeof != 1")

    Calculator::calculate(games, users)

    respond_to do |format|
      format.html
    end
  end  

  def get_statistics    

    users = User.where("typeof != 1")
    game_id = params[:game_id] if params[:game_id].present?
    game = Game.find(game_id)
    Rails.logger.info("Game_id: #{game_id}")

    stats = Calculator::getStatistics(game, users)

    game_mr = game.match_results(:order => "team_id ASC")

    homeTeam = game_mr.first.team.name
    awayTeam = game_mr.last.team.name

    respond_to do |format|
      Rails.logger.info('TESTE DE RETORNO DO get_statistics')
      Rails.logger.info("VARIAVEL #{stats}")
      format.json { render json: {matches: stats[0], wins: stats[1], draws: stats[2], defeats: stats[3], homeTeam: homeTeam, awayTeam: awayTeam} }
    end

  end

end

app/helpers/hints_helper.rb
module HintsHelper
end

app/views/hints/_form.html.erb
<%= form_for(@hint) do |f| %>
  <% if @hint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hint.errors.count, "error") %> prohibited this hint from being saved:</h2>

      <ul>
      <% @hint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :home_goals %><br />
    <%= f.number_field :home_goals %>
  </div>
  <div class="field">
    <%= f.label :away_goals %><br />
    <%= f.number_field :away_goals %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.number_field :game_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hints/_left_sidebar.html.erb
<div class="left_sidebar">
	<ul>
        <li id="myhints_LI" class="current"><a class="current" href="<%=hints_path%>">Meus Palpites</a><img src=""/></li>
        <li id="edit_LI"><a href="<%=edit_user_path(user_id)%>">Editar Dados</a><img src=""></li>
        <li id="allhints_LI"><a href="<%=all_hints_path%>">Todos os Palpites</a><img src=""></li>
        <li id="ranking_LI"><a href="<%=ranking_path%>">Ranking</a><img src=""></li>
     </ul>
     <div class="bottom-img-container">
        <img src="<%=asset_path('tatu-bola1.png')%>" alt="Mascote">
     </div>
</div>

<script type="text/javascript">
		
	jQuery(function() {

		function setCurrentItemLeftMenu(jElement){

	      jElement.addClass("current");
	      jElement.children(":first-child").addClass("current");	     

	      jElement.siblings().each(function(){
	        
	        var currentLI = jQuery(this);

	        if (currentLI.is(".current")){

	          currentLI.removeClass("current");
	          currentLI.children(":first-child").removeClass("current");
	        }          
	      });
	    }


		//Verifica qual valor da variavel :locals => {:var_control} que é submetido na view que renderiza esta partial.
	    var control = '<%=var_control%>';

	    if (control == '1')
	      setCurrentItemLeftMenu(jQuery("#myhints_LI"));
	    else if (control == '2')
	      setCurrentItemLeftMenu(jQuery("#edit_LI"));
	    else if (control == '3')
	      setCurrentItemLeftMenu(jQuery("#allhints_LI"));
	    else if (control == '4')
	      setCurrentItemLeftMenu(jQuery("#ranking_LI"));
	});

</script>

app/views/hints/admin_all_hints.html.erb
<div class="wrap_hint">
  <%= render :partial => 'hints/left_sidebar', :locals => {:user_id => @user.id, :var_control => '3'} %>
  <div class="right_container">
  	<h2>Palpites de Todos os Participantes</h2>
  	
  	<a href="<%=calculator_path%>" style="margin-left: 50px;">Calcular Pontuação!</a> 

  	<div id="accordion" class="acc-faq">
    	
        <% @games.each do |game| %>
        	<% game_mr = game.match_results(:order => "team_id ASC") %>
        	<% msgStatusHintHeader = game.closed ? "Palpites Encerrados" : "Palpites Disponíveis" %>
		    <h3><%=l game.gamedate, :format => :complete%>, <%=l game.gametime, :format => :smallshort%>, <%=game.local%><span class="status_hint_header">&nbsp;&nbsp;<%=msgStatusHintHeader%></span></h3>    
			    <div class="hints_list">
			        <ul>
			        	<% if game.computed %>
				        	<li style="border: 3px solid rgb(78, 231, 6);">
						        <div class="game_result_hint">
					              <div class="flag_placar">
					                <img src="<%=asset_path(game_mr.first.team.logotipo.to_s)%>"/>
					                <span class="goal_first" gameid="<%=game.id%>" teamid="<%=game_mr.first.team_id%>" type="text"><%=game_mr.first.goals%></span>
					                <label>X</label>
					                <span class="goal_last" gameid="<%=game.id%>" teamid="<%=game_mr.last.team_id%>" type="text"><%=game_mr.last.goals%></span>
					                <img src="<%=asset_path(game_mr.last.team.logotipo.to_s)%>"/>
					              </div>
					              <div class="flag_abbrev">
					                <label class="first_abbrev_name"> <%=game_mr.first.team.abbrev%> </label>
					                <label class="sec_abbrev_name"> <%=game_mr.last.team.abbrev%> </label>
					              </div>
					            </div>
					            <div class="game_counting">
					            	<label style="font-size: 18px;">Resultado Oficial</label>
					            </div>
					        </li>
				        <% end %>
			        	<% @users.each do |user| %>
			        		<% unless user.typeof == 1 %>
				        		<li>
							        <div class="game_result_hint">
						              <div class="flag_placar"> 
						              	<% hometeamid = game_mr.first.team.id %>
						                <% awayteamid = game_mr.last.team.id %>
						                <img src="<%=asset_path(game_mr.first.team.logotipo.to_s)%>"/>
						                <%
						                	unless user.hints.nil? && user.hints.empty?
						                		homeTeamHint = user.hints.find_by_game_id_and_team_id(game.id, hometeamid);
						                		awayTeamHint = user.hints.find_by_game_id_and_team_id(game.id, awayteamid);

						                		if homeTeamHint.nil?
						                			homeTeamHintGoals = ""
						                		else
						                			homeTeamHintGoals = homeTeamHint.goals
						                		end

												if awayTeamHint.nil?
						                			awayTeamHintGoals = ""
						                		else
						                			awayTeamHintGoals = awayTeamHint.goals
						                		end			                		
						                	end
						                %>
						                <span class="goal_first" gameid="<%=game.id%>" teamid="<%=hometeamid%>" type="text"><%=homeTeamHintGoals%></span>
						                <label>X</label>
						                <span class="goal_last" gameid="<%=game.id%>" teamid="<%=awayteamid%>" type="text"><%=awayTeamHintGoals%></span>
						                <img src="<%=asset_path(game_mr.last.team.logotipo.to_s)%>"/>
						              </div>
						              <div class="flag_abbrev">
						                <label class="first_abbrev_name"> <%=game_mr.first.team.abbrev%> </label>
						                <label class="sec_abbrev_name"> <%=game_mr.last.team.abbrev%> </label>
						              </div>
						            </div>
						            <div class="game_counting">
						              <label gameid="<%=game.id%>"><%=user.name%>&nbsp;<%=user.lastname%></label><br>
						              <label gameid="<%=game.id%>" style="color: #000;"><%= "#{homeTeamHint.points} pontos" unless homeTeamHint.nil? %></label>
						            </div>
						        </li>
						    <% end %>    
				        <%end%>
			        </ul>
			    </div>
	    <% end %>
	</div>
  </div>
</div>

<%= javascript_include_tag 'jquery-ui-1.10.3.custom.min' %>
<%=stylesheet_link_tag 'jquery-ui-1.10.3.custom'%>
<script type="text/javascript">
	jQuery("#accordion").accordion({heightStyle: "content", animate: 200});
</script>

app/views/hints/calculator.html.erb
<div style="background-color: #CCC">
	<%= link_to 'Voltar para todos os palpites', admin_all_hints_path %>
</div>

app/views/hints/edit.html.erb
<h1>Editing hint</h1>

<%= render 'form' %>

<%= link_to 'Show', @hint %> |
<%= link_to 'Back', hints_path %>

app/views/hints/index.html.erb
<div class="wrap_hint">
  <%= render :partial => 'left_sidebar', :locals => {:user_id => @user.id, :var_control => '1'} %>
  <div class="right_container">
    <div class="games_list">
      <ul>
        <% @games.each do |game| %>
          <% game_mr = game.match_results(:order => "team_id ASC") %>
          <li>
            <div class="game_info">
              <% dateofgame = game.gamedate 
                 timeofgame = game.gametime
              %>
              <input id= "date_<%=game.id%>" type="hidden" year="<%=dateofgame.year%>" month="<%=dateofgame.month%>" day="<%=dateofgame.day%>" hour="<%=timeofgame.hour%>" minutes="<%=timeofgame.min%>"/>
              <span><%=l game.gamedate, :format => :complete%></span><br>
              <span><%=l game.gametime, :format => :smallshort%></span><br>
              <span> <%=game.local%> </span>
            </div>
            <div class="game_result_hint">
              <div class="flag_placar">
                <img src="<%=asset_path(game_mr.first.team.logotipo.to_s)%>"/>
                <% hometeamid = game_mr.first.team.id %>
                <% awayteamid = game_mr.last.team.id %>
                <% unless game.hints.nil? && game.hints.empty?
                    arraymatchhomehints = game.hints.find_all_by_user_id_and_team_id(@user.id, hometeamid)
                    arraymatchawayhints = game.hints.find_all_by_user_id_and_team_id(@user.id, awayteamid)
                  end
                  unless arraymatchhomehints.nil? && arraymatchhomehints.empty?
                    unless arraymatchhomehints.first.nil? 
                      homegoals = arraymatchhomehints.first.goals
                    end
                  end
                  unless arraymatchawayhints.nil? && arraymatchawayhints.empty?
                    unless arraymatchawayhints.first.nil? 
                      awaygoals = arraymatchawayhints.first.goals
                    end
                  end
                %>
                <input class="goal_first" gameid="<%=game.id%>" teamid="<%=hometeamid%>" type="text" value="<%=homegoals%>"/>
                <label>X</label>
                <input class="goal_last" gameid="<%=game.id%>" teamid="<%=awayteamid%>" type="text" value="<%=awaygoals%>"/>
                <img src="<%=asset_path(game_mr.last.team.logotipo.to_s)%>"/>
              </div>
              <div class="save_placar">
                <input type="button" class="save_hint submit_btn blue_qdt_input" value="Salvar"/>
              </div>
              <div class="flag_abbrev">
                <label id="first"> <%=game_mr.first.team.abbrev%> </label>
                <label class="statistics"> Estatísticas </label>
                <label id="last"> <%=game_mr.last.team.abbrev%> </label>
                <span class="hint_process_saved">Palpite Salvo!</span>
              </div>
            </div>
            <div class="game_counting">
              <label id="status" gameid="<%=game.id%>">Aberto</label><br>
              <span>Fecha <%=l game.gamedate, :format => :default%> às <%=l game.gametime-30.minutes, :format => :smallshort%></span>              
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    
    <div id="dialog" title="Estatísticas">
      <label id="match-hints-computed"></label>
      <div class="container-progress-bar"> 
        <label id="home-team-name-stats" class="label-team-name"></label>
        <div id="progressbar-wins"></div>
        <label id="home-team-value-stats" class="label-team-stats"></label>
      </div>
      <div class="container-progress-bar">
        <label id="draw-stats" class="label-team-name">Empate</label>
        <div id="progressbar-draws"></div>
        <label id="draw-value-stats" class="label-team-stats"></label>
      </div>
      <div class="container-progress-bar">
        <label id="away-team-name-stats" class="label-team-name"></label>
        <div id="progressbar-defeats"></div>
        <label id="away-team-value-stats" class="label-team-stats"></label>
      </div>
    </div>

  </div>
</div>

<script type="text/javascript">
jQuery(function() {

  checkHintStatus();

  function saveHints (inpt) {

    var hints = [];

    var game_id = jQuery(inpt.parent().prev().find(':input')[0]).attr('gameid');
    
    if (checkDates(game_id)) {

      alert("Não é possível salvar o palpite pois o tempo limite já expirou.");
      
    } else {

      var hint1 = {
        userid: "<%=@user.id%>",
        teamid: jQuery(inpt.parent().prev().find(':input')[0]).attr('teamid'),
        gameid: game_id,
        goals: inpt.parent().prev().find(':input')[0].value
      };

      var hint2 = {
        userid: "<%=@user.id%>",
        teamid: jQuery(inpt.parent().prev().find(':input')[1]).attr('teamid'),
        gameid: game_id,
        goals: inpt.parent().prev().find(':input')[1].value
      };
      
      hints.push(hint1);
      hints.push(hint2);

      var saved = sendHints(inpt, hints);

      return saved;
    }
  }

  function sendHints (inpt, arrayhints) {

    jQuery.ajax('<%=save_hint_path%>',{
      data : getJSONFromHere(arrayhints),
      success : function (data, textStatus, jqXHR) {

        //Tiver que tirar lá de baixo no evento do btn.
        showProcessedMsg(inpt, data.saved);

        if (data.saved) {
          return true          

        } else {
          return false
        }
      }      
    });

  }

  function sendGameID (game_id, gameId) {

    jQuery.ajax('<%=get_statistics_path%>',{
      data : getJSONStatistics(game_id),
      success : function (data, textStatus, jqXHR) {

        //Tiver que tirar lá de baixo no evento do btn.
        showWindowStatistics(data.matches, data.wins, data.draws, data.defeats, data.homeTeam, data.awayTeam);        
      }      
    });

  }

  function getJSONFromHere(arrayhints) {
    
    var hint = {
      array_hints: arrayhints
    }

    return hint;
  }

  function getJSONStatistics(gameid) {
    
    var gameId = {
      game_id: gameid
    }

    return gameId;
  }

  function checkHintStatus () {
    console.log("checked");
    
    var jLabel;
    var game_id;
    

    statusArray = jQuery(".game_counting").find("label");
    jQuery.each(statusArray, function(index, value) {
      jLabel = jQuery(value);
      game_id = jLabel.attr('gameid');
      
      //Se retornar true, o tempo pro palpite expirou             
      if (checkDates(game_id)) {
        
        if (!jLabel.hasClass("closedStatus")){
          jLabel.addClass("closedStatus");
          jLabel.text("Fechado");
          //Localizar as inputs e desabilita-las
          jQuery(jLabel.parent().prev().find(":input")[0]).prop('disabled', true);
          jQuery(jLabel.parent().prev().find(":input")[1]).prop('disabled', true);
          jQuery(jLabel.parent().prev().find(":input")[2]).hide();
          //jQuery(jQuery(".goal_first")[0]).prop('disabled', true)

        }
      }

    });
  }

  //Se retornar true, o tempo pro palpite expirou
  function checkDates(game_id) {
    
    var rbdate = jQuery("#date_"+game_id);
   
    var jDate = new Date(rbdate.attr('year'), parseInt(rbdate.attr('month'))-1, rbdate.attr('day'), rbdate.attr('hour'), rbdate.attr('minutes'), 0);

    var jCurrentDate = new Date();

    return checkExpiredHints(jDate, jCurrentDate);
  }

  function checkExpiredHints(gameDate, currentDate) {

    var minutesCount = (gameDate - currentDate)/60000;//Obtendo os minutos restantes para partida
    
    //Tempo expirado para os palpites se retornar true
    if ( minutesCount < 30)
      return true
    else
      return false
  }

  function showProcessedMsg(inpt, saved) {    
    
    var jSpan = jQuery(inpt.parent().next().find("span")[0]);
    if (saved) {
      
      if (jSpan.hasClass("not_saved_error")) {
        jSpan.removeClass("not_saved_error");
        jSpan.text("Palpite Salvo!");
      }

    } else {
     
      jSpan.addClass("not_saved_error");
      jSpan.text("Erro ao Salvar!");
    }

    jSpan.fadeTo('fast', 1);
    
    setTimeout(function() {
      jSpan.fadeTo(800, 0);
    }, 3000);

  }

  function showWindowStatistics(matches, wins, draws, defeats, homeTeam, awayTeam) {
    console.log("Home Team x Away Team", homeTeam, awayTeam)
    console.log("Numero de Palpites, Vitorias, Empates, Derrotas: ", matches, wins, draws, defeats);
    
    jQuery("#dialog").dialog("open");

    jQuery("#match-hints-computed").text("Foram computados " + matches + " palpites até o momento.");

    jQuery(function() {
      
      jQuery("#progressbar-wins").progressbar({
        value: parseFloat(wins)
      });

      jQuery("#home-team-name-stats").text(homeTeam);
      jQuery("#home-team-value-stats").text(wins.toString() + "%");
      jQuery("#progressbar-wins").addClass("progressbar-bolao");
      jQuery("#progressbar-wins").find(".ui-progressbar-value").addClass("progressbar-bolao-bar");

      jQuery("#progressbar-draws").progressbar({
        value: parseFloat(draws)
      });
            
      jQuery("#draw-value-stats").text(draws.toString() + "%");
      jQuery("#progressbar-draws").addClass("progressbar-bolao");
      jQuery("#progressbar-draws").find(".ui-progressbar-value").addClass("progressbar-bolao-bar");

      jQuery("#progressbar-defeats").progressbar({
        value: parseFloat(defeats)
      });
      
      jQuery("#away-team-name-stats").text(awayTeam);
      jQuery("#away-team-value-stats").text(defeats.toString() + "%");
      jQuery("#progressbar-defeats").addClass("progressbar-bolao");
      jQuery("#progressbar-defeats").find(".ui-progressbar-value").addClass("progressbar-bolao-bar");
      
    });
  }

  //Events
  jQuery('.save_hint').click(function() {
    
    var inpt = jQuery(this);
    
    var bool = saveHints(inpt);
    
    //console.log("bool do saveHint no evento: ", bool);    
    
  });

  jQuery('.statistics').click(function() {

    var jLabel = jQuery(this);
    var game_id = jQuery(jLabel.parent().prev().prev().find(':input')[0]).attr('gameid');
    console.log("GameId: ", game_id);

    sendGameID(game_id);    
  });

  jQuery("#dialog").dialog({
    autoOpen: false,
    height: 220,
    width: 456,
    show: {
      effect: "clip",
      duration: 300
    },
    hide: {
      effect: "clip",
      duration: 300
    }
  });

  setInterval(checkHintStatus, 100000);

});
</script>

app/views/hints/new.html.erb
<h1>New hint</h1>

<%= render 'form' %>

<%= link_to 'Back', hints_path %>