config/routes.rb
BolaoApp::Application.routes.draw do

  resources :match_results
  resources :games
  resources :teams
  resources :hints
  resources :users

  root :to => 'main#index'

  match 'admin/index' => 'admin#index', :as => :admin

  match 'index' => 'main#index', :as => :index
  match 'cadastro' => 'main#cadastro', :as => :cadastro
  match 'ranking' => 'main#ranking', :as => :ranking
  match 'regras' => 'main#regras', :as => :regras

  match 'login/index' => 'login#index', :as => :login
  match 'login/do_login' => 'login#do_login', :as => :login_do_login
  match 'login/do_logout' => 'login#do_logout', :as => :logout

  match 'hints/result/savehint' => 'hints#saveHint', :as => :save_hint
  match 'hints/result/allhints' => 'hints#all_hints', :as => :all_hints  
  match 'hints/result/adminallhints' => 'hints#admin_all_hints', :as => :admin_all_hints
  match 'hints/result/calculator' => 'hints#calculator', :as => :calculator
  match 'hints/result/get_statistics' => 'hints#get_statistics', :as => :get_statistics

  match 'users/:id/reset_score' => 'users#reset_score', :as => :user_reset_score
  match 'users/calculate/reset_all_scores' => 'users#reset_all_scores', :as => :reset_all_scores
  match 'users/calculate/reset_all_hintspoints' => 'users#reset_all_hintspoints', :as => :reset_all_hintspoints

end

app/views/admin/index.html.erb
<h2>Seção de Administração</h2>
<h3>
	<div class="admin_teams_div">
		<ul>
			<li>
				<%= link_to 'Listar Participantes', users_path %>
			</li>
			<li>
				<%= link_to 'Listar Times', teams_path %>
			</li>
			<li>
				<%= link_to 'Listar Jogos', games_path %>
			</li>
			<li>
				<%= link_to 'Listar Confrontos', match_results_path %>
			</li>
			<li>
				<%= link_to 'Listar Palpites para Cálculo da Pontuação', admin_all_hints_path %>
			</li>
		</ul>
	</div>
</h3>