config/routes.rb
BolaoApp::Application.routes.draw do

  resources :match_results
  resources :games
  resources :teams
  resources :hints
  resources :users

  root :to => 'main#index'

  match 'admin/index' => 'admin#index', :as => :admin

  match 'index' => 'main#index', :as => :index
  match 'cadastro' => 'main#cadastro', :as => :cadastro
  match 'ranking' => 'main#ranking', :as => :ranking
  match 'regras' => 'main#regras', :as => :regras

  match 'login/index' => 'login#index', :as => :login
  match 'login/do_login' => 'login#do_login', :as => :login_do_login
  match 'login/do_logout' => 'login#do_logout', :as => :logout

  match 'hints/result/savehint' => 'hints#saveHint', :as => :save_hint
  match 'hints/result/allhints' => 'hints#all_hints', :as => :all_hints  
  match 'hints/result/adminallhints' => 'hints#admin_all_hints', :as => :admin_all_hints
  match 'hints/result/calculator' => 'hints#calculator', :as => :calculator
  match 'hints/result/get_statistics' => 'hints#get_statistics', :as => :get_statistics

  match 'users/:id/reset_score' => 'users#reset_score', :as => :user_reset_score
  match 'users/calculate/reset_all_scores' => 'users#reset_all_scores', :as => :reset_all_scores
  match 'users/calculate/reset_all_hintspoints' => 'users#reset_all_hintspoints', :as => :reset_all_hintspoints

end

app/models/user.rb
class User < ActiveRecord::Base 
  
  attr_accessible :email, :lastname, :name, :password, :password_confirmation, :email_confirmation, :score, :typeof
  attr_accessor :password_confirmation, :email_confirmation

  has_many :hints

  USER_TYPE = {
                ADMIN: {id: 1, name: 'Administrator'},
                PLAYER: {id: 2, name: 'Regular User'}                
              }

  validates :name, :presence => true
  validates :lastname, :presence => true

  validates :email, :presence => true, :uniqueness => true
  

  validates :email_confirmation, :presence => true
  
  validates :password, :presence => true, :length => { :in => 4..20 }
  validates :password_confirmation, :presence => true, on: :create

  validate :validatePassword, :reduce => true, on: :create
  validate :validateEmail

  def validatePassword
    if new_record? && !password.eql?(password_confirmation)
      errors.add(:password, ' e confirmacao devem ser iguais')
    end
  end
 
 def validateEmail
    if !email.eql?(email_confirmation)
      errors.add(:email, ' e confirmacao devem ser iguais')
    end
 end

 def self.authenticate email, password
    
    return false if email.nil?
    return false if password.nil?

    if !email.index('@').nil?
      user = User.find_by_email(email)
    end

    user && password.eql?(user.password) ? user : nil
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  skip_before_filter :require_login
  skip_before_filter :require_admin, :only => [:new, :create, :edit, :update]

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    #return if redirect_if_logged
    if logged_in?
      flash[:notice] = "#{current_user.name} #{current_user.lastname}, voce ja esta logado, efetue o logout antes de realizar um novo cadastro."
    end
    @user = User.new
    
    respond_to do |format|
      format.html      
    end
  end

  # GET /users/1/edit
  def edit
    
    @user = User.find(params[:id])
    @user.email_confirmation = params[:email_confirmation] unless params[:email_confirmation].nil?
    
    respond_to do |format|
      format.html # index.html.erb
    end

  end

  # POST /users
  # POST /users.json
  def create
    
    if logged_in?
      #flash[:notice] = "#{current_user.name} #{current_user.lastname}, voce ja esta logado, efetue o logout antes de realizar um novo cadastro"
      @user = User.new
      return render action: :new
    end

    @user = User.new(:name => params[:user][:name], :lastname => params[:user][:lastname], :email => params[:user][:email].downcase, :password => params[:user][:password], :typeof => 2, :score => 0)    

    respond_to do |format|
           
      @user.password_confirmation = params[:user][:password_confirmation]
      @user.email_confirmation = params[:user][:email_confirmation].downcase

      if @user.save
        flash[:notice] = 'Voce foi cadastrado com sucesso e ja pode elaborar seus palpites.'
        format.html { redirect_to controller: :login, action: :do_login, user: {:email => @user.email, :password => @user.password}}
      else
        format.html { render action: "new" }
      end

    end

  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    
    @user = User.find(params[:id])

    respond_to do |format|

      @user.email_confirmation = params[:user][:email_confirmation].downcase

      if @user.update_attributes(:name => params[:user][:name], :lastname => params[:user][:lastname], :email => params[:user][:email].downcase)
        
        flash[:notice] = "Dados atualizados com sucesso!!"
        format.html { redirect_to :controller => :users, :action => :edit, :id =>  @user.id}

      else
                
        format.html { render action: "edit", :id => @user.id, :email_confirmation => @user.email_confirmation}

      end

    end

  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def reset_score
    @user = User.find(params[:id])
      
    @user.email_confirmation = @user.email.downcase
    @user.update_attributes(:name => @user.name, :lastname => @user.lastname, :email => @user.email.downcase, :score => 0)

    respond_to do |format|
      format.html
    end
  end

  def reset_all_scores
    users = User.all

    users.each do |user|
      user.email_confirmation = user.email.downcase
      user.update_attributes(:name => user.name, :lastname => user.lastname, :email => user.email.downcase, :score => 0)      
    end

    respond_to do |format|
      format.html
    end
  end

  def reset_all_hintspoints
    users = User.all(:include => :hints)

    users.each do |user|
      hints = user.hints
      hints.each do |hint|
        hint.update_attributes(:points => 0)
      end
    end

    respond_to do |format|
      format.html
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%=form_for(@user, html: {class: "form-horizontal"}) do |f| %>
    <% if flash[:notice] %>
        <div class="flash-notice"><span><%= flash[:notice] %></span></div>
    <% end %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <% @status = @user.new_record? ? "cadastrar" : "atualizar" %>
          <h3><%= pluralize(@user.errors.count, "erro") %> ao <%=@status%> usuário:</h3>

          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
    <% end %>

    <div id="div_id_name" class="control-group">
        <%=f.text_field :name, :placeholder => "Seu Nome" %>
    </div>

    <div id="div_id_lastname" class="control-group">
        <%=f.text_field :lastname, :placeholder => "Seu Sobrenome" %>
    </div>

    <div id="div_id_email" class="control-group">
        <%=f.text_field :email, :placeholder => "Seu Email" %>
    </div>

    <div id="div_id_email" class="control-group">
        <%=f.text_field :email_confirmation, :placeholder => "Confirme Seu Email" %>
    </div>

    <% if @user.new_record? %>
        <div id="div_id_password1" class="control-group">
            <%=f.password_field :password, :placeholder => "Digite uma senha" %>
        </div>
        <div id="div_id_password2" class="control-group">
            <%=f.password_field :password_confirmation, :placeholder => "Confirme a senha" %>
        </div>
    <% end %>

    <div class="actions">
        <%= f.submit :class => "submit_btn blue_qdt_input" %>
    </div>
<% end %>

app/views/users/edit.html.erb
<div class="wrap_hint">
  <%= render :partial => 'hints/left_sidebar', :locals => {:user_id => @user.id, :var_control => '2'} %>
  <div class="right_container">
  	<h2>Edite seus Dados</h2>
  	<%= render :partial => 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="admin_teams">
  <tr>
    <th>Name</th>
    <th>Lastname</th>
    <th>Email</th>
    <th>Password</th>
    <th>Score</th>
    <th>Hints Points (total)</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.lastname %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= user.score %></td>
    <% unless user.hints.empty? %>
        <% countHintPoints = 0 %>
        <% user.hints.each do |hint| %>
            <% countHintPoints += hint.points unless hint.points.nil? %>
        <% end %>
    <% end %>    
    <td><%= countHintPoints %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<div class="admin_teams_div">
    <%= link_to 'New User', new_user_path %>
    <%= link_to 'Reset All Scores', reset_all_scores_path %>
    <%= link_to 'Reset All Hints Points', reset_all_hintspoints_path %>
</div>

app/views/users/new.html.erb
<h2>Cadastrar Novo Participante</h2>

<%= render :partial => "form", :locals => {:input_value => 'Cadastrar'} %>

<script type="text/javascript">
	
	jQuery(function(){

		jQuery(jQuery("#header #menu ul li")[2]).find("p").addClass("current");
	});
	
</script>

app/views/users/reset_all_hintspoints.html.erb
<div style="background-color: #CCC">
	<%= link_to 'Voltar para lista de usuarios', users_path %>
</div>

app/views/users/reset_all_scores.html.erb
<div style="background-color: #CCC">
	<%= link_to 'Voltar para lista de usuarios', users_path %>
</div>

app/views/users/reset_score.html.erb
<div style="background-color: #CCC">
	<%= link_to 'Voltar para usuario', @user %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% if @user.typeof.to_i == User::USER_TYPE[:ADMIN][:id]  %>

  <p>
    <b>Name:</b>
    <%= @user.name %>
  </p>

  <p>
    <b>Lastname:</b>
    <%= @user.lastname %>
  </p>

  <p>
    <b>Email:</b>
    <%= @user.email %>
  </p>

  <p>
    <b>Password:</b>
    <%= @user.password %>
  </p>

  <p>
    <b>Score:</b>
    <%= @user.score %>
  </p>

  <%= link_to 'Reset Score', user_reset_score_path(@user.id) %> |
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>

  <style type="text/css">
    body {
      background-color: #CCC;
    }
  </style>

<% end %>